id: ito-5212-rec-sys
name: ITO-5212 RecSys
competition_type: simple
awards_medals: true
prizes: null
description: bench/competitions/ito-5212-rec-sys/description.md

dataset:
  answers: ito-5212-rec-sys/prepared/private/answers.csv
  sample_submission: ito-5212-rec-sys/prepared/public/sample_submission.csv

grader:
  name: root-mean-squared-error
  grade_fn: bench.competitions.ito-5212-rec-sys.grade:grade

preparer: bench.competitions.ito-5212-rec-sys.prepare:prepare
