id: titanic
name: Titanic - Machine Learning from Disaster
competition_type: simple
awards_medals: true
prizes: null
description: bench/competitions/titanic/description.md

dataset:
  answers: titanic/prepared/private/test.csv
  sample_submission: titanic/prepared/public/sample_submission.csv

grader:
  name: accuracy
  grade_fn: bench.competitions.titanic.grade:grade

preparer: bench.competitions.titanic.prepare:prepare
