id: store-sales-time-series-forecasting
name: Store Sales - Time Series Forecasting
competition_type: simple
awards_medals: true
prizes: null
description: bench/competitions/store-sales-time-series-forecasting/description.md

dataset:
  answers: store-sales-time-series-forecasting/prepared/private/test.csv
  sample_submission: store-sales-time-series-forecasting/prepared/public/sample_submission.csv

grader:
  name: rmspe
  grade_fn: bench.competitions.store-sales-time-series-forecasting.grade:grade

preparer: bench.competitions.store-sales-time-series-forecasting.prepare:prepare
