id: rossmann-store-sales
name: Rossman Store Sales
competition_type: simple
awards_medals: true
prizes:
  - position: 1
    value: 15000
  - position: 2
    value: 10000
  - position: 3
    value: 5000
description: bench/competitions/rossmann-store-sales/description.md

dataset:
  answers: rossmann-store-sales/prepared/private/answers.csv
  sample_submission: rossmann-store-sales/prepared/public/sample_submission.csv

grader:
  name: rmspe
  grade_fn: bench.competitions.rossmann-store-sales.grade:grade

preparer: bench.competitions.rossmann-store-sales.prepare:prepare
