id: santander-product-recommendation
name: Santander Product Recommendation
competition_type: simple
awards_medals: true
prizes:
  - position: 1
    value: 30000
  - position: 2
    value: 20000
  - position: 3
    value: 10000
description: bench/competitions/santander-product-recommendation/description.md

dataset:
  answers: santander-product-recommendation/prepared/private/answers.csv
  sample_submission: santander-product-recommendation/prepared/public/sample_submission.csv

grader:
  name: MAP@7
  grade_fn: bench.competitions.santander-product-recommendation.grade:grade

preparer: bench.competitions.santander-product-recommendation.prepare:prepare
