id: house-prices-advanced-regression-techniques
name: House Prices - Advanced Regression Techniques
competition_type: simple
awards_medals: true
prizes: null
description: bench/competitions/house-prices-advanced-regression-techniques/description.md

dataset:
  answers: house-prices-advanced-regression-techniques/prepared/private/test.csv
  sample_submission: house-prices-advanced-regression-techniques/prepared/public/sample_submission.csv

grader:
  name: root-mean-squared-error
  grade_fn: bench.competitions.house-prices-advanced-regression-techniques.grade:grade

preparer: bench.competitions.house-prices-advanced-regression-techniques.prepare:prepare
