id: amex-default-prediction
name: "American Express - Default Prediction"
competition_type: simple
awards_medals: true
prizes:
  - position: 1
    value: 40000
  - position: 2
    value: 30000
  - position: 3
    value: 20000
  - position: 4
    value: 10000
description: bench/competitions/amex-default-prediction/description.md
dataset:
  answers: amex-default-prediction/prepared/private/answers.csv
  sample_submission: amex-default-prediction/prepared/public/sample_submission.csv

grader:
  name: amex-metric
  grade_fn: bench.competitions.amex-default-prediction.grade:grade

preparer: bench.competitions.amex-default-prediction.prepare:prepare
